### ISSUE TITLE
user may use a homedir of /root

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-launcher#21]
see what we would need to make this work without error:

```
lokinet launcher version 0.8 registered
setting permissions to pepe
user pepe uid is 1001 homedir is /root
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, chown '/root/.loki'
    at Object.chownSync (fs.js:1090:3)
    at /usr/lib/node_modules/loki-launcher/modes/fix-perms.js:100:10
    at /usr/lib/node_modules/loki-launcher/uid.js:99:5
    at ChildProcess.exithandler (child_process.js:285:7)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
```

**Comment by neuroscr** [comment]
maybe I'll put a warning on it (if you're not root and using /root), something like "specified user is sharing a home directory potentially with your root user, you may still run into permission problems. Suggest you set a different home directory for specified user and run this command again"

**Comment by neuroscr** [comment]
found bug in the user homedir detection, new patch pushed (but not yet published)

**Comment by neuroscr** [comment]
just going to close this, we don't need to yet worry about that level of chaos
