### ISSUE TITLE
run prequal when lokid is running

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-launcher#22]
```
lokinet launcher version 0.8 registered
Starting open port check on configured RPC port: 22023
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::22023
    at Server.setupListenHandle [as _listen2] (net.js:1279:14)
    at listenInCluster (net.js:1327:12)
    at Server.listen (net.js:1414:7)
    at Object.serveTCP (/usr/lib/node_modules/loki-launcher/lets_tcp.js:464:12)
    at portTest (/usr/lib/node_modules/loki-launcher/modes/prequal.js:162:33)
    at module.exports (/usr/lib/node_modules/loki-launcher/modes/prequal.js:194:3)
    at Object.<anonymous> (/usr/lib/node_modules/loki-launcher/index.js:223:42)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
Emitted 'error' event at:
    at emitErrorNT (net.js:1306:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by neuroscr** [comment]
handled error more gracefully in 0.0.7
