### ISSUE TITLE
"storageServer.version" is not owned by user creating the Loki Launcher

### ISSUE THREAD

**Issue by MartinJakomin** [loki-project/loki-launcher#53]
**Describe the bug**
"Permission denied" exception occurs when running lokid at the time Loki tries to start the storage server: ` Caught exception: Error: EACCES: permission denied, open '/opt/loki-launcher/var/storageServer.version'`.

**To Reproduce**
Just follow the Service node Guide at https://lokidocs.com/ServiceNodes/SNFullGuide/#express-setup-guide. I am using Debian 9 and I am not sure if this affects other OS too.

**To Solve**
Change the ownership of the storageServer.version from root to the user running the Loki launcher (e.g. "snode").

**Screenshots or Logs**
```
Jul 23 08:48:46 debian index.js[451]: **************************************************************
Jul 23 08:48:46 debian index.js[451]: Outputting logs to /home/snode/.loki/storage/storage.logs
Jul 23 08:48:46 debian index.js[451]: [2019-07-23 08:48:46.113] [info] Loki Storage Server v1.0.2
Jul 23 08:48:46 debian index.js[451]:  git commit hash: 8ba5286
Jul 23 08:48:46 debian index.js[451]:  build time: 2019-07-15T07:54:30Z
Jul 23 08:48:46 debian index.js[451]: Caught exception: Error: EACCES: permission denied, open '/opt/loki-launcher/var/storageServer.version'
Jul 23 08:48:46 debian index.js[451]: fs.js:114
Jul 23 08:48:46 debian index.js[451]:     throw err;
Jul 23 08:48:46 debian index.js[451]:     ^
Jul 23 08:48:46 debian index.js[451]: Error: EACCES: permission denied, open 'launcher_exception.log'
Jul 23 08:48:46 debian index.js[451]:     at Object.openSync (fs.js:443:3)
Jul 23 08:48:46 debian index.js[451]:     at Object.writeFileSync (fs.js:1194:35)
Jul 23 08:48:46 debian index.js[451]:     at Object.appendFileSync (fs.js:1240:6)
Jul 23 08:48:46 debian index.js[451]:     at process.<anonymous> (/usr/lib/node_modules/loki-launcher/daemon.js:21:6)
Jul 23 08:48:46 debian index.js[451]:     at process.emit (events.js:198:13)
Jul 23 08:48:46 debian systemd[1]: lokid.service: Main process exited, code=exited, status=7/NOTRUNNING
Jul 23 08:48:50 debian systemd[1]: lokid.service: Unit entered failed state.
Jul 23 08:48:50 debian systemd[1]: lokid.service: Failed with result 'exit-code'.
Jul 23 08:49:21 debian systemd[1]: lokid.service: Service hold-off time over, scheduling restart.
Jul 23 08:49:21 debian systemd[1]: Stopped lokilauncher.
```

**Additional Information (please complete the following information):**
 - Operating System: Debian 9
-  Remote node
 - Version of Loki daemon: 4.0.3

**Comment by neuroscr** [comment]
This seems to be resolved.
